DROP TABLE PROPERTIES;
CREATE TABLE PROPERTIES 
( 
    KEY       VARCHAR2(300),
    LANG      VARCHAR2(2),
    TEXT      VARCHAR2(3000),
    CONSTRAINT PROPERTIES_PK PRIMARY KEY(KEY, LANG)
);

SELECT * FROM PROPERTIES;