DROP TABLE TEST_TRANSLATION;
CREATE TABLE TEST_TRANSLATION ( 
    FILENAME      VARCHAR2(300),
    ID       VARCHAR2(300),
    LANG      VARCHAR2(2),
    CONTENTS      VARCHAR2(4000),
    CONSTRAINT TEST_TRANSLATION_PK PRIMARY KEY(FILENAME,ID, LANG)
);
SELECT * FROM TEST_TRANSLATION;